import {
  IconApps,
  IconBarrierBlock,
  IconBoxSeam,
  IconChartHistogram,
  IconChecklist,
  IconComponents,
  IconError404,
  IconExclamationCircle,
  IconHexagonNumber1,
  IconHexagonNumber2,
  IconHexagonNumber3,
  IconHexagonNumber4,
  IconHexagonNumber5,
  IconLayoutDashboard,
  IconMessages,
  IconRouteAltLeft,
  IconServerOff,
  IconSettings,
  IconTruck,
  IconUserShield,
  IconUsers,
  IconLock,
} from "@tabler/icons-react";

export const SidebarLinks = [
  {
    title: "Dashboard",
    label: "",
    href: "/dashboard",
    icon: <IconLayoutDashboard size={18} />,
  },
  {
    title: "Users",
    label: "3",
    href: "/users",
    icon: <IconChecklist size={18} />,
  },
  {
    title: "Comming Soon",
    label: "3",
    href: "/comming-soon",
    icon: <IconChecklist size={18} />,
  },
  {
    title: "404 Error",
    label: "3",
    href: "/error-404",
    icon: <IconError404 size={18} />,
  },
  {
    title: "Apps",
    href: "/apps",
    icon: <IconApps size={18} />,
  },
  {
    title: "Sub Menu",
    label: "10",
    href: "/sub-menu",
    icon: <IconRouteAltLeft size={18} />,
    sub: [
      {
        title: "Trucks",
        label: "9",
        href: "/trucks",
        icon: <IconTruck size={18} />,
      },
      {
        title: "Cargos",
        label: "",
        href: "/cargos",
        icon: <IconBoxSeam size={18} />,
      },
    ],
  },
  //   {
  //     name: "Users",
  //     route: "users",
  //     icon: IconUsers,
  //   },
];
